import type { Doc } from "../_generated/dataModel";

type MessageDocument = Omit<Doc<"messages">, "_id" | "_creationTime">;
type SeedMessage = Omit<
  MessageDocument,
  "category" | "urgency" | "summary" | "draftReply"
> &
  Required<
    Pick<MessageDocument, "category" | "urgency" | "summary" | "draftReply">
  >;

export const SEED_MESSAGES = [
  {
    sender: "Tenant Cedar-204",
    subject: "Water spreading beneath the kitchen sink",
    body: "I found water pooling under the kitchen sink when I got home. The cabinet floor is soaked and the leak seems to be coming from the supply line, so I shut off the small valve under the basin. Please let me know what I should do next.",
    channel: "form",
    status: "classified",
    category: "damage",
    urgency: "high",
    summary: "Water is pooling beneath the kitchen sink, and the tenant has shut off the apparent supply valve. The wet cabinet may need prompt inspection to prevent further damage.",
    draftReply: "Thank you for shutting off the valve and letting us know. Please keep the area clear and avoid using the sink; we will coordinate an urgent plumbing inspection and update you with an arrival window as soon as one is confirmed.",
    classifiedAt: 1_735_689_600_000,
  },
  {
    sender: "Tenant Juniper-118",
    subject: "Cracked bedroom window after last night's wind",
    body: "There is a long crack across the inside pane of the bedroom window. It is still in place and I do not see loose glass, but I have kept the children away from it. Could someone assess whether it needs to be boarded or replaced?",
    channel: "webhook",
    status: "classified",
    category: "damage",
    urgency: "medium",
    summary: "A bedroom window has a long crack, though the pane remains in place and no loose glass is reported. The tenant has kept children away and requests an assessment.",
    draftReply: "I’m sorry this happened, and thank you for keeping everyone clear of the window. Please do not press on the pane or attempt a repair; we’ll arrange an inspection and let you know the expected timing once the visit is scheduled.",
    classifiedAt: 1_735_776_000_000,
  },
  {
    sender: "Tenant Harbor-307",
    subject: "Possible gas odor near the range",
    body: "I noticed a rotten-egg smell near the stove when I came into the apartment. I have not turned on any burners. I am stepping outside now and need instructions on who to contact.",
    channel: "form",
    status: "classified",
    category: "damage",
    urgency: "high",
    summary: "The tenant reports a possible gas odor near the stove and is leaving the apartment without operating the burners. This is an immediate safety concern.",
    draftReply: "Please stay outside and do not use switches, flames, or appliances in the apartment. From a safe location, call your gas utility’s emergency line or local emergency services now; notify us once you are safe, and we will coordinate property access after the area is cleared.",
    classifiedAt: 1_735_862_400_000,
  },
  {
    sender: "Tenant Maple-512",
    subject: "Ceiling stain growing in the hall",
    body: "A yellow-brown stain appeared on the hallway ceiling yesterday and looks a little wider this morning. It is not dripping at the moment. I took a photo and can send it if helpful.",
    channel: "webhook",
    status: "classified",
    category: "damage",
    urgency: "medium",
    summary: "A hallway ceiling stain has grown since yesterday, although there is no active dripping. The source should be checked for a possible leak.",
    draftReply: "Thanks for reporting the change and documenting it. Please avoid disturbing the area and let us know if it begins to drip or bulge; we’ll arrange an inspection and share a time window when it is confirmed.",
    classifiedAt: 1_735_948_800_000,
  },
  {
    sender: "Tenant Alder-221",
    subject: "Small scorch mark beside the outlet",
    body: "I noticed a dark mark on the wall beside the living-room outlet after plugging in a lamp. There was no smoke or sparking, and I unplugged the lamp. Could maintenance take a look before I use the outlet again?",
    channel: "form",
    status: "classified",
    category: "damage",
    urgency: "high",
    summary: "A dark scorch mark appeared beside a living-room outlet after use, with no smoke or sparking reported. The tenant has unplugged the lamp and is avoiding the outlet.",
    draftReply: "Thank you for unplugging the lamp and reporting this. Please leave that outlet unused and do not remove its cover; we’ll request an electrician’s assessment and confirm the visit timing as soon as it is arranged.",
    classifiedAt: 1_736_035_200_000,
  },
  {
    sender: "Tenant Birch-409",
    subject: "Water came in under balcony door during storm",
    body: "After the rain last night I found a damp strip of carpet just inside the balcony door. I have blotted it up and moved a bookcase away from the wall. The door is closed now, but the seal may not be sitting right.",
    channel: "webhook",
    status: "classified",
    category: "damage",
    urgency: "medium",
    summary: "Rainwater entered beneath the balcony door and dampened a strip of carpet. The tenant blotted the area and moved furniture away from the wall.",
    draftReply: "I’m sorry the rain got inside, and thank you for moving the bookcase. Please keep the area ventilated if practical and tell us if moisture returns; we’ll inspect the door seal and check for hidden dampness, then share the planned timing.",
    classifiedAt: 1_736_121_600_000,
  },
  {
    sender: "Tenant Willow-105",
    subject: "Radiator stays cold in the back room",
    body: "The radiator in the back bedroom stays cold even when the others are warm. I checked that its dial is turned up, but I have not tried bleeding it. The room is getting chilly overnight.",
    channel: "form",
    status: "classified",
    category: "maintenance",
    urgency: "medium",
    summary: "The back-bedroom radiator remains cold while other radiators work, leaving the room chilly overnight. The tenant has not attempted a repair.",
    draftReply: "I’m sorry that room is uncomfortable. Please leave the radiator controls as they are rather than opening the valve; we’ll arrange a heating check and let you know the appointment window once confirmed.",
    classifiedAt: 1_736_208_000_000,
  },
  {
    sender: "Tenant Lark-330",
    subject: "Bathroom tap keeps dripping",
    body: "The bathroom sink tap drips steadily even when I turn it firmly off. It is not overflowing, but the sound is noticeable at night. Please let me know if maintenance can replace the washer or check the faucet.",
    channel: "webhook",
    status: "classified",
    category: "maintenance",
    urgency: "low",
    summary: "The bathroom faucet continues to drip when turned off, creating noise at night but no overflow. The tenant requests a maintenance check.",
    draftReply: "Thanks for flagging the dripping tap. Please avoid forcing the handle tighter, as that could worsen wear; we’ll add it to the maintenance schedule and send you the proposed visit window.",
    classifiedAt: 1_736_294_400_000,
  },
  {
    sender: "Tenant Moss-614",
    subject: "Dishwasher stops before the cycle finishes",
    body: "Our dishwasher starts normally but stops about halfway through a cycle and leaves the dishes wet. I checked that the door is latched and there is no standing water. Could someone inspect it?",
    channel: "form",
    status: "classified",
    category: "maintenance",
    urgency: "medium",
    summary: "The dishwasher repeatedly stops mid-cycle and leaves dishes wet, despite a latched door and no standing water. The tenant requests an inspection.",
    draftReply: "I’m sorry the dishwasher is interrupting your routine. Thank you for checking the door and noting there is no standing water; please avoid running repeated cycles, and we’ll arrange an appliance inspection and share the timing when booked.",
    classifiedAt: 1_736_380_800_000,
  },
  {
    sender: "Tenant Fern-708",
    subject: "Bedroom closet door has come off its track",
    body: "One sliding panel of the bedroom closet has slipped off its track and is leaning safely against the wall. I did not try to lift it back into place. Please send someone to rehang it when available.",
    channel: "webhook",
    status: "classified",
    category: "maintenance",
    urgency: "low",
    summary: "A sliding closet panel has come off its track and is leaning against the wall. The tenant has not attempted to rehang it.",
    draftReply: "Thanks for letting us know and for leaving the panel alone. Please keep the area clear until it is secured; we’ll schedule a maintenance visit and provide an estimated window once available.",
    classifiedAt: 1_736_467_200_000,
  },
  {
    sender: "Tenant Plover-416",
    subject: "Kitchen exhaust fan rattles loudly",
    body: "The exhaust fan above the stove has developed a loud rattling sound. It still turns on and I do not smell anything unusual, but I have stopped using it in case a part is loose.",
    channel: "form",
    status: "classified",
    category: "maintenance",
    urgency: "medium",
    summary: "The kitchen exhaust fan runs with a new loud rattle, and the tenant has stopped using it because a part may be loose. No unusual odor is reported.",
    draftReply: "I understand how disruptive that sound can be. Please keep the fan off until it is checked; we’ll arrange a maintenance inspection and let you know when a technician can attend.",
    classifiedAt: 1_736_553_600_000,
  },
  {
    sender: "Tenant Sable-823",
    subject: "Ants appearing along the pantry baseboard",
    body: "I have seen a small line of ants along the pantry baseboard on three mornings this week. I wiped the area and stored open food in sealed containers. Could you advise whether pest control can inspect?",
    channel: "webhook",
    status: "classified",
    category: "maintenance",
    urgency: "medium",
    summary: "Ants have appeared along the pantry baseboard on several mornings. The tenant has cleaned the area and sealed open food.",
    draftReply: "Thank you for taking those steps and letting us know the sightings are recurring. Please keep food sealed and avoid applying pesticides until we coordinate; we’ll check the appropriate pest-control schedule and update you on next steps.",
    classifiedAt: 1_736_640_000_000,
    approvedAt: 1_736_726_400_000,
  },
  {
    sender: "Tenant Cove-932",
    subject: "Hot water takes several minutes to reach shower",
    body: "The shower eventually gets hot, but it takes around six minutes in the morning. The kitchen tap seems normal. Is this expected for the building, or should someone check the bathroom line?",
    channel: "form",
    status: "classified",
    category: "maintenance",
    urgency: "low",
    summary: "The shower takes about six minutes to deliver hot water while the kitchen tap seems normal. The tenant asks whether the bathroom line should be checked.",
    draftReply: "Thanks for describing the timing and comparing it with the kitchen tap. We can have maintenance check the bathroom fixture and line; please share whether the delay occurs at other times too, and we’ll follow up with a visit window.",
    classifiedAt: 1_736_726_400_000,
    approvedAt: 1_736_812_800_000,
    resolvedAt: 1_736_899_200_000,
  },
  {
    sender: "Tenant Dune-117",
    subject: "Question about partial rent payment receipt",
    body: "I paid the first portion of this month's rent through the portal yesterday and plan to pay the balance on Friday. The portal shows the transaction, but I cannot find a receipt to download. Could you tell me where it is recorded?",
    channel: "webhook",
    status: "classified",
    category: "billing",
    urgency: "medium",
    summary: "The tenant made a partial rent payment and cannot locate a downloadable receipt in the portal. They plan to pay the remaining balance on Friday.",
    draftReply: "Thank you for checking with us. We can review the payment record and point you to the receipt once it is visible in the account; please include the transaction date if you follow up, and continue to use the portal for the remaining payment.",
    classifiedAt: 1_736_812_800_000,
  },
  {
    sender: "Tenant Quarry-258",
    subject: "Late fee appears after payment submitted",
    body: "I submitted rent on the last day of the grace period and the bank shows it as processing. My account now lists a late fee. Could you explain whether the fee is based on submission or when the transfer clears?",
    channel: "form",
    status: "classified",
    category: "billing",
    urgency: "medium",
    summary: "A late fee appeared while the tenant’s rent transfer, submitted during the grace period, is still processing. They ask how payment timing is assessed.",
    draftReply: "I understand why the timing is concerning. Please keep the bank confirmation for your records; we’ll review the account entry and applicable payment timeline, then explain whether an adjustment is appropriate.",
    classifiedAt: 1_736_899_200_000,
  },
  {
    sender: "Tenant Reed-645",
    subject: "Deposit statement question about cleaning charge",
    body: "I received the move-out deposit statement and would like clarification on the cleaning charge. I left the unit swept and have photos from the handover. Could you send the itemized basis for this deduction?",
    channel: "webhook",
    status: "classified",
    category: "billing",
    urgency: "low",
    summary: "The former tenant requests an itemized explanation of a cleaning deduction from the deposit and says they have handover photos.",
    draftReply: "Thank you for reaching out and keeping the handover photos. We’ll review the statement and available inspection notes, then provide the itemized information we have and explain how to raise any remaining questions.",
    classifiedAt: 1_736_985_600_000,
    approvedAt: 1_737_072_000_000,
  },
  {
    sender: "Tenant Finch-390",
    subject: "Utility charge seems higher than usual",
    body: "The shared utility charge on this month's statement is almost twice last month's, although our household routine has not changed. Could you confirm the billing period and how the building share is calculated?",
    channel: "form",
    status: "classified",
    category: "billing",
    urgency: "medium",
    summary: "The shared utility charge is nearly twice the previous month despite no reported change in household routine. The tenant asks about the billing period and calculation.",
    draftReply: "I can see why that increase stands out. We’ll check the statement period and the allocation details for this charge, then send an explanation; if you have a copy of the prior statement, it may help us compare the entries.",
    classifiedAt: 1_737_072_000_000,
  },
  {
    sender: "Tenant Gale-571",
    subject: "Autopay seems to have withdrawn rent twice",
    body: "My bank activity shows two rent-sized withdrawals from the property portal this morning. One is marked pending, so I am not sure whether it will settle. Please check whether both transactions are associated with my account.",
    channel: "webhook",
    status: "classified",
    category: "billing",
    urgency: "high",
    summary: "The tenant sees two rent-sized portal withdrawals, one still pending, and asks whether both are linked to the account. A duplicate charge could affect available funds.",
    draftReply: "I’m sorry for the uncertainty. Please do not submit another payment while we review the entries; keep the transaction references, and we’ll compare the portal records and explain the next steps once the pending item updates.",
    classifiedAt: 1_737_158_400_000,
  },
  {
    sender: "Tenant Flint-044",
    subject: "Could I split next month's rent into two dates?",
    body: "My payroll date is changing next month, and I wanted to ask whether a one-time split payment arrangement might be available. I have not changed the scheduled payment yet. Please let me know the process and any deadlines.",
    channel: "form",
    status: "classified",
    category: "billing",
    urgency: "low",
    summary: "The tenant asks whether a one-time split payment arrangement may be available because of a payroll-date change. No payment settings have been changed.",
    draftReply: "Thank you for asking ahead of time. We can explain the available payment options and any approval deadlines, but cannot confirm an arrangement until it is reviewed; please share the dates you have in mind so we can advise you.",
    classifiedAt: 1_737_244_800_000,
  },
  {
    sender: "Tenant Pebble-286",
    subject: "Laundry room machine still out of order",
    body: "The left washer in the shared laundry room has had an out-of-order note for several days. I reported it earlier this week but have not seen an update. Could you let residents know the repair status or expected timing?",
    channel: "webhook",
    status: "classified",
    category: "complaint",
    urgency: "medium",
    summary: "The left shared washer remains out of order several days after a prior report, and residents have not received an update. The tenant asks for repair timing.",
    draftReply: "I’m sorry the lack of an update has been frustrating. We’ll check the current repair status and share what timing is available; we’ll avoid promising a completion date until the service provider confirms it.",
    classifiedAt: 1_737_331_200_000,
  },
  {
    sender: "Tenant North-751",
    subject: "Repeated quiet-hours noise from courtyard",
    body: "There has been loud music from the courtyard after midnight on three nights this week. I have not approached the group because I do not feel comfortable doing so. Could management remind residents of the quiet-hours policy?",
    channel: "form",
    status: "classified",
    category: "complaint",
    urgency: "medium",
    summary: "The tenant reports loud courtyard music after midnight on several nights and does not feel comfortable approaching the group. They request a quiet-hours reminder.",
    draftReply: "I’m sorry the repeated noise has affected your rest. Thank you for reporting it; we’ll review the concern and determine an appropriate reminder to residents. If there is an immediate safety issue, please contact local emergency services.",
    classifiedAt: 1_737_417_600_000,
  },
  {
    sender: "Tenant Atlas-669",
    subject: "Package shelf blocks the lobby entrance",
    body: "Packages have been left across the lobby entrance again, making it difficult to bring a stroller through. This has happened several times recently. Could the delivery area be marked more clearly or checked during the day?",
    channel: "webhook",
    status: "classified",
    category: "complaint",
    urgency: "medium",
    summary: "Packages repeatedly obstruct the lobby entrance, making it difficult for the tenant to pass with a stroller. They ask for clearer delivery-area guidance or monitoring.",
    draftReply: "Thank you for explaining how the obstruction affects access. We’ll review the delivery-area setup and consider a clearer reminder; please let us know if the entrance becomes fully blocked so we can assess the immediate access concern.",
    classifiedAt: 1_737_504_000_000,
  },
  {
    sender: "Tenant Lumen-180",
    subject: "Hallway light has been flickering for weeks",
    body: "The light outside the third-floor stairwell flickers most evenings. I mentioned it to the desk last week, but it is still happening and makes the landing hard to see. Please let me know if it is on the repair list.",
    channel: "form",
    status: "classified",
    category: "complaint",
    urgency: "medium",
    summary: "A third-floor hallway light continues to flicker weeks after it was reported, making the landing difficult to see. The tenant asks whether repair is planned.",
    draftReply: "I’m sorry this has continued without a clear update. We’ll check whether a repair request is open and arrange an assessment if needed; please use the well-lit route where possible until we can confirm the work timing.",
    classifiedAt: 1_737_590_400_000,
    approvedAt: 1_737_676_800_000,
    resolvedAt: 1_737_763_200_000,
  },
  {
    sender: "Tenant Saffron-542",
    subject: "Cleaning schedule for the shared lounge",
    body: "The lounge tables and floor have been left dirty after the weekend on several occasions. I understand use varies, but could you share how often the area is cleaned and where residents should report missed service?",
    channel: "webhook",
    status: "classified",
    category: "complaint",
    urgency: "low",
    summary: "The tenant says the shared lounge has repeatedly been left dirty after weekends and asks about cleaning frequency and reporting missed service.",
    draftReply: "Thank you for raising this, and I’m sorry the lounge has not been consistently clean. We’ll confirm the current cleaning schedule and the right channel for reporting a missed visit, then share that information with you.",
    classifiedAt: 1_737_676_800_000,
    approvedAt: 1_737_763_200_000,
  },
  {
    sender: "Tenant Sol-303",
    subject: "¿A qué hora puedo recoger las llaves?",
    body: "Mi contrato empieza el lunes y quería saber a qué hora puedo recoger las llaves. También quisiera confirmar si debo llevar algún documento. Gracias por la orientación.",
    channel: "form",
    status: "classified",
    category: "general",
    urgency: "low",
    summary: "The tenant’s lease begins Monday, and they ask when keys can be collected and whether identification is required.",
    draftReply: "Gracias por escribirnos. Podemos confirmar el horario de entrega y los documentos necesarios antes del lunes; por favor indíquenos si prefiere recoger las llaves por la mañana o por la tarde para orientarle mejor.",
    classifiedAt: 1_737_763_200_000,
  },
  {
    sender: "Tenant Arroyo-827",
    subject: "¿Se permiten bicicletas en el cuarto de almacenamiento?",
    body: "Quisiera guardar una bicicleta en el cuarto común de almacenamiento, pero no encuentro las reglas del edificio sobre ese espacio. ¿Me podrían indicar si está permitido y si hay que registrar la bicicleta?",
    channel: "webhook",
    status: "classified",
    category: "general",
    urgency: "low",
    summary: "The tenant asks whether bicycles may be stored in the shared storage room and whether registration is required.",
    draftReply: "Con gusto le ayudamos a revisar las reglas del espacio común. Confirmaremos si se permiten bicicletas y si hace falta registrarlas; mientras tanto, le recomendamos no dejarla allí hasta recibir esa confirmación.",
    classifiedAt: 1_737_849_600_000,
  },
  {
    sender: "Tenant Brisa-194",
    subject: "¿Dónde se solicita una llave adicional?",
    body: "Se mudó un familiar que me visita con frecuencia y quería preguntar cómo solicitar una llave adicional para la entrada. ¿Hay un formulario o algún costo que deba conocer?",
    channel: "form",
    status: "classified",
    category: "general",
    urgency: "low",
    summary: "The tenant asks how to request an additional building-entry key and whether a form or fee applies.",
    draftReply: "Gracias por consultarnos. Le indicaremos el procedimiento para solicitar una llave adicional y cualquier cargo aplicable; por seguridad, no copie ni encargue una llave hasta confirmar el proceso con administración.",
    classifiedAt: 1_737_936_000_000,
  },
  {
    sender: "Tenant Nube-468",
    subject: "¿Hay espacio para estacionar una bicicleta?",
    body: "Voy a empezar a usar bicicleta para ir al trabajo y quisiera saber si el edificio tiene un lugar seguro para estacionarla. No quiero dejarla en un pasillo ni bloquear una salida.",
    channel: "webhook",
    status: "classified",
    category: "general",
    urgency: "low",
    summary: "The tenant asks whether the building has a secure bicycle parking area and wants to avoid obstructing a hallway or exit.",
    draftReply: "Gracias por tener en cuenta las rutas de salida. Revisaremos qué opciones de estacionamiento para bicicletas ofrece el edificio y le compartiremos las indicaciones; por favor no la deje en pasillos ni frente a una salida.",
    classifiedAt: 1_738_022_400_000,
  },
  {
    sender: "Tenant Cielo-739",
    subject: "¿Cuál es el procedimiento para reservar la sala común?",
    body: "Mi familia viene de visita el próximo mes y quisiera reservar la sala común por unas horas. ¿Me pueden compartir los horarios disponibles, las reglas de uso y si se necesita dejar un depósito?",
    channel: "form",
    status: "classified",
    category: "general",
    urgency: "low",
    summary: "The tenant asks how to reserve the shared room next month and requests availability, usage rules, and deposit information.",
    draftReply: "Con gusto le compartimos los pasos para reservarla. Revisaremos los horarios disponibles, las reglas y si se requiere depósito; si nos indica el día aproximado y la duración, podremos orientarle con más precisión.",
    classifiedAt: 1_738_108_800_000,
  },
  {
    sender: "Tenant Meadow-055",
    subject: "Question about move-in elevator booking",
    body: "I am moving into the building next Saturday and would like to reserve the service elevator. What hours are available, and how far ahead should I submit the request?",
    channel: "webhook",
    status: "classified",
    category: "general",
    urgency: "low",
    summary: "The incoming tenant asks about service-elevator availability and the lead time required for a move-in reservation next Saturday.",
    draftReply: "Welcome to the building. We can check the service-elevator schedule and explain the reservation lead time; please share your preferred arrival window, and we’ll let you know what options are available.",
    classifiedAt: 1_738_195_200_000,
    approvedAt: 1_738_281_600_000,
  },
] satisfies SeedMessage[];
